name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

env:
  REGION: "us-central1"                             # デプロイ先のリージョン
  IMAGE_NAME: ${{ github.event.repository.name }}   # Docker イメージ名
  SERVICE_NAME: ${{ github.event.repository.name }} # Cloud Run のサービス名

jobs:
  deploy:
    runs-on: ubuntu-latest
    # CIが「成功」して完了した場合のみ、このジョブを実行する
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Workload Identity で OIDCトークンを取得するために必須の設定
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v7

      # 1. buildx のセットアップ
      - uses: docker/setup-buildx-action@v3

      # 2. Workload Identity Federation を使って Google Cloud へ認証
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.PROJECT_ID }}
          token_format: 'access_token'

      # 3. Docker を GCP Artifact Registry にログインさせる
      - name: Docker Auth to GCP
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          # WIFの場合はユーザー名を「oauth2accesstoken」にする
          username: oauth2accesstoken
          # パスワードには発行した一時的な「access_token」を指定する
          password: ${{ steps.auth.outputs.access_token }}

      # 4. GitHub Actions側でビルド ＆ プッシュ
      - name: Build and Push Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          # (注) latest に加えて ${{ github.sha }} を指定する流派もあるが、ここでは最新のみ保存する
          tags: ${{ secrets.GAR_REPO_URL }}/${{ env.IMAGE_NAME }}:latest
          # GitHub Actionsの高速なキャッシュを利用
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 5. build したイメージを Cloud Run へデプロイ
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ secrets.GAR_REPO_URL }}/${{ env.IMAGE_NAME }}:latest
          flags: |
            --cpu-boost
            --max-instances=1
          secrets: |
            LINE_CHANNEL_SECRET=LINE_CHANNEL_SECRET:latest
            LINE_CHANNEL_ACCESS_TOKEN=LINE_CHANNEL_ACCESS_TOKEN:latest

      - run: echo "Deployed URL ${{ steps.deploy.outputs.url }}"
