name: Proxy CI

on:
  workflow_call:

defaults:
  run:
    working-directory: ./proxy

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "proxy/go.mod"
          cache-dependency-path: "proxy/go.sum"

      - name: Check code formatting
        run: test -z "$(gofmt -l .)"

      - name: Run tests with coverage
        run: go test -v -cover ./...
